import Head from "next/head";
import {
	AiFillTwitterCircle,
	AiFillLinkedin,
	AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import React from "react";


export default function Admin() {
	const [darkMode, setDarkMode] = useState(true);

	return (
    <div className={darkMode ? "dark" : ""}>
<Head>
<title>Breaking Bakes</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/pastel.ico" />
</Head>

<main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
<section className="">
	<nav className="py-10 mb-12 flex justify-between dark:text-white">
        <a href="/"><h1 className="font-burtons text-xl">Breaking Bakes</h1></a>
		<ul className=" items-center hidden md:flex">
		<li>
			<BsFillMoonStarsFill
			onClick={() => setDarkMode(!darkMode)}
			className=" cursor-pointer text-2xl"
			/>
		</li>

		<li>
			<a
			className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
			href="/"
			>
			Salir
			</a>
		</li>
		</ul>
            </nav>
        </section>

        <section className="flex flex-col ">
        <section className="h-10 bg-white">

        </section>
        <section className=" h-10 bg-green-500-">

        </section>

        <section className="flex flex-col items-center min-h-screen py-2 bg-white dark:bg-gray-900">
            <div>
                <table className="shadow-lg bg-white table-auto  dark:bg-slate-400 ">

                <tr>
                    <th className="bg-teal-600 border text-center border-teal-600 px-8 py-4" >Status</th>
                    <th className="bg-teal-600 border text-center border-teal-600 px-8 py-4" >Full Name</th>
                    <th className="bg-teal-600 border text-center border-teal-600 px-8 py-4 ">Country</th>
                    <th className="bg-teal-600 border text-center border-teal-600 px-8 py-4 ">Description</th> 
                    <th className="bg-teal-600 border text-center border-teal-600 px-8 py-4 ">Description</th>
                    <th className="bg-teal-600 border text-center border-teal-600  px-8 py-4">Total Amount</th>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4">Delivered</td>
                    <td className="border px-8 py-4">John Smith</td>
                    <td className="border px-8 py-4">USA</td> 
                    <td className="border px-8 py-4">John Smith</td>
                    <td className="border px-8 py-4">A small cake shop in the heart of New York City</td>
                    <td className="border px-8 py-4">$10</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4">Hold</td>
                    <td className="border px-8 py-4">Jane Doe</td>
                    <td className="border px-8 py-4">Canada</td> 
                    <td className="border px-8 py-4">A large cake shop in the heart of Toronto</td>
                    <td className="border px-8 py-4">$20</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4">Delivered</td>
                    <td className="border px-8 py-4">John Smith</td>
                    <td className="border px-8 py-4">USA</td> 
                    <td className="border px-8 py-4">A small cake shop in the heart of New York City</td>
                    <td className="border px-8 py-4">$10</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4"></td>
                    <td className="border px-8 py-4">Jane Doe</td>
                    <td className="border px-8 py-4">Canada</td> 
                    <td className="border px-8 py-4">A large cake shop in the heart of Toronto</td>
                    <td className="border px-8 py-4">$20</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4"></td>
                    <td className="border px-8 py-4">John Smith</td>
                    <td className="border px-8 py-4">USA</td> 
                    <td className="border px-8 py-4">A small cake shop in the heart of New York City</td>
                    <td className="border px-8 py-4">$10</td>
                </tr>
                <tr>
                <td className="border px-8 py-4"></td>
                    <td className="border px-8 py-4">Jane Doe</td>
                    <td className="border px-8 py-4">Canada</td> 
                    <td className="border px-8 py-4">A large cake shop in the heart of Toronto</td>
                    <td className="border px-8 py-4">$20</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4">Delivered</td>
                    <td className="border px-8 py-4">John Smith</td>
                    <td className="border px-8 py-4">USA</td> 
                    <td className="border px-8 py-4">A small cake shop in the heart of New York City</td>
                    <td className="border px-8 py-4">$10</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4"></td>
                    <td className="border px-8 py-4">Jane Doe</td>
                    <td className="border px-8 py-4">Canada</td> 
                    <td className="border px-8 py-4">A large cake shop in the heart of Toronto</td>
                    <td className="border px-8 py-4">$20</td>
                </tr>
                <tr className="text-center">
                <td className="border px-8 py-4">Delivered</td>
                    <td className="border px-8 py-4">John Smith</td>
                    <td className="border px-8 py-4">USA</td> 
                    <td className="border px-8 py-4">A small cake shop in the heart of New York City</td>
                    <td className="border px-8 py-4">$10</td>
                </tr>

                </table>
            </div>
        </section>
        </section>

        </main>

        <footer className="p-4 bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
        <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 <a href="https://github.com/NevercomeG" className="hover:underline">NevercomeG</a>. All Rights Reserved.
        </span>
        <ul className="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <a href="#" className="mr-4 hover:underline md:mr-6 ">About</a>
        </li>
        <li>
            <a href="#" className="mr-4 hover:underline md:mr-6">Privacy Policy</a>
        </li>
        <li>
            <a href="#" className="mr-4 hover:underline md:mr-6">Licensing</a>
        </li>
        <li>
            <a href="#" className="hover:underline">Contact</a>
        </li>
    </ul>
</footer>

</div>
);
}